### ISSUE TITLE
What is the IDE for this project?

### ISSUE THREAD

**Issue by phuocnguyenke159** [Jana-Marie/stm32g4xx_usb_cdc#1]
Hi Henrik,

I saw the cubeMX file in your project.
I was trying to import your project into SMT32CubeIDE, but it not compatible.
May you tell me what is IDE that you used?

Thanks
Phuoc.

**Comment by Jana-Marie** [comment]
Hey, no dedicated IDE was used. I work with Makefiles + editor of your choice. To build the project run `make`
